study_name: "Force01"

dataset:
  db_file: dataset/force01.h5
  label: CalcForceForNodes

train:
  epoch: 300
  activation: "relu"
  device: "cuda"
  optimizer: "adam"

tuning:
  trials: 100
  hidden_layers_sizes: [128, 256, 512]
  n_hidden_layers: [0,1,2,3]
  lr_values: [0.001, 0.01, 0.1]
  batch_size_values: [128, 512, 1024]
